vim.api.nvim_set_hl(0, 'Comment', { fg = colors.purple, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = colors.pink })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = colors.cyan })

vim.api.nvim_set_hl(0, 'PmenuSel', { fg = 'NONE', bg = colors.bg3 })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = 'NONE', bg = colors.bg2 })

vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { fg = colors.fg, bg = 'NONE', strikethrough = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { fg = colors.pink, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg = colors.pink, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { fg = colors.purple, bg = 'NONE', italic = true })

vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', { fg = colors.bg, bg = colors.blue })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = colors.bg, bg = colors.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { fg = colors.bg, bg = colors.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { fg = colors.bg, bg = colors.green })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = colors.bg, bg = colors.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', { fg = colors.bg, bg = colors.lightblue })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { fg = colors.bg, bg = colors.lightblue })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = colors.bg, bg = colors.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = colors.bg, bg = colors.darkcyan })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = colors.bg, bg = colors.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = colors.bg, bg = colors.darkcyan })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = colors.bg, bg = colors.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = colors.bg, bg = colors.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = colors.bg, bg = colors.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = colors.bg, bg = colors.green })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = colors.bg, bg = colors.darkcyan })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = colors.bg, bg = colors.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = colors.bg, bg = colors.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = colors.bg, bg = colors.purple })

vim.api.nvim_set_hl(0, 'HopNextKey', { fg = colors.darkpink, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'HopNextKey1', { fg = colors.cyan, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'HopNextKey2', { fg = colors.darkcyan, bg = 'NONE', bold = false })
vim.api.nvim_set_hl(0, 'HopPreview', { fg = colors.bg, bg = colors.darkpink })

vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = colors.darkpink, bg = 'NONE', bold = true })

