vim.api.nvim_set_hl(0, 'Comment', { fg = COLORS.purple, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = COLORS.pink })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = COLORS.cyan })

vim.api.nvim_set_hl(0, 'PmenuSel', { fg = 'NONE', bg = COLORS.bg3 })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = 'NONE', bg = COLORS.bg2 })

vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { fg = COLORS.fg, bg = 'NONE', strikethrough = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { fg = COLORS.pink, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg = COLORS.pink, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { fg = COLORS.purple, bg = 'NONE', italic = true })

vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', { fg = COLORS.bg, bg = COLORS.blue })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = COLORS.bg, bg = COLORS.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { fg = COLORS.bg, bg = COLORS.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { fg = COLORS.bg, bg = COLORS.green })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = COLORS.bg, bg = COLORS.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', { fg = COLORS.bg, bg = COLORS.lightblue })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { fg = COLORS.bg, bg = COLORS.lightblue })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = COLORS.bg, bg = COLORS.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = COLORS.bg, bg = COLORS.darkcyan })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = COLORS.bg, bg = COLORS.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = COLORS.bg, bg = COLORS.darkcyan })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = COLORS.bg, bg = COLORS.pink })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = COLORS.bg, bg = COLORS.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = COLORS.bg, bg = COLORS.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = COLORS.bg, bg = COLORS.green })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = COLORS.bg, bg = COLORS.darkcyan })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = COLORS.bg, bg = COLORS.blue2 })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = COLORS.bg, bg = COLORS.purple })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = COLORS.bg, bg = COLORS.purple })

vim.api.nvim_set_hl(0, 'HopNextKey', { fg = COLORS.darkpink, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'HopNextKey1', { fg = COLORS.cyan, bg = 'NONE', bold = true })
vim.api.nvim_set_hl(0, 'HopNextKey2', { fg = COLORS.darkcyan, bg = 'NONE', bold = false })
vim.api.nvim_set_hl(0, 'HopPreview', { fg = COLORS.bg, bg = COLORS.darkpink })

vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = COLORS.darkpink, bg = 'NONE', bold = true })

vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteWarn', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteSpecial', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteNote', { fg = COLORS.blue2, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteDefault', { fg = COLORS.blue2, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteOk', { fg = COLORS.blue2, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewBlockQuoteError', { fg = COLORS.darkpink, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'MarkviewCheckboxCancelled', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewCheckboxChecked', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewCheckboxPending', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewCheckboxProgress', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewCheckboxUnchecked', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewCheckboxStriked', { fg = COLORS.pink, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'MarkviewInlineCode', { fg = COLORS.pink, bg = COLORS.bg2 })
vim.api.nvim_set_hl(0, 'MarkviewCodeInfo', { fg = COLORS.pink, bg = COLORS.bg1 })
vim.api.nvim_set_hl(0, 'MarkviewCode', { fg = 'NONE', bg = COLORS.bg1 })

vim.api.nvim_set_hl(0, 'MarkviewIcon1', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewIcon1Sign', { fg = COLORS.pink, bg = COLORS.bg3 })
vim.api.nvim_set_hl(0, 'MarkviewIcon1Fg', { fg = COLORS.pink, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'MarkviewHeading1', { fg = COLORS.pink, bg = COLORS.bg2, bold = true })
vim.api.nvim_set_hl(0, 'MarkviewHeading2', { fg = COLORS.darkcyan, bg = COLORS.bg2, bold = true })
vim.api.nvim_set_hl(0, 'MarkviewHeading3', { fg = COLORS.blue2, bg = COLORS.bg2, bold = true })
vim.api.nvim_set_hl(0, 'MarkviewHeading4', { fg = COLORS.blue2, bg = COLORS.bg2, bold = true })
vim.api.nvim_set_hl(0, 'MarkviewHeading5', { fg = COLORS.blue2, bg = COLORS.bg2, bold = true })
vim.api.nvim_set_hl(0, 'MarkviewHeading6', { fg = COLORS.blue2, bg = COLORS.bg2, bold = true })

vim.api.nvim_set_hl(0, 'MarkviewListItemStar', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewListItemPlus', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewListItemMinus', { fg = COLORS.pink, bg = 'NONE' })

vim.api.nvim_set_hl(0, 'MarkviewEmail', { fg = COLORS.purple, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewImageLink', { fg = COLORS.purple, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewHyperlink', { fg = COLORS.pink, bg = 'NONE', underline = true })

vim.api.nvim_set_hl(0, 'MarkviewTableHeader', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewTableBorder', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewTableAlignCenter', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewTableAlignLeft', { fg = COLORS.pink, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MarkviewTableAlignRight', { fg = COLORS.pink, bg = 'NONE' })

vim.api.nvim_set_hl(0, '@markup.heading.1.markdown', { fg = COLORS.pink, bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.2.markdown', { fg = COLORS.darkcyan, bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.3.markdown', { fg = COLORS.blue2, bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.4.markdown', { fg = COLORS.blue2, bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.5.markdown', { fg = COLORS.blue2, bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.6.markdown', { fg = COLORS.blue2, bold = true })
vim.api.nvim_set_hl(0, '@markup.raw.markdown_inline', { fg = COLORS.pink, bg = COLORS.bg2 })
vim.api.nvim_set_hl(0, '@markup.list.markdown', { fg = COLORS.pink })

vim.api.nvim_set_hl(0, 'MdHighlight', { fg = COLORS.bg, bg = COLORS.blue2 })

