return {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    branch = 'main',
    build = ':TSUpdate',
    config = function()
        require('nvim-treesitter').install({
            'asm',
            'bash',
            'c',
            'cmake',
            'cpp',
            'css',
            'csv',
            'diff',
            'dockerfile',
            'gitignore',
            'html',
            'http',
            'ini',
            'java',
            'javascript',
            'json',
            'latex',
            'lua',
            'make',
            'markdown',
            'markdown_inline',
            'python',
            'regex',
            'rust',
            'sql',
            'toml',
            'typescript',
            'typst',
            'vim',
            'vimdoc',
            'vue',
            'xcompose',
            'xml',
            'yaml',
        })
    end,
}
